[workspace]
members = ["crates/*"]

[package]
name = "maidenx"
version = "0.1.0-dev"
description = "Rust ML Framework for Maiden Engine"
license = "MIT OR Apache-2.0"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"
publish = true
repository = "https://github.com/miniex/maidenx"
documentation = "https://docs.rs/maidenx"
readme = "README.md"
keywords = ["gpu", "maiden"]
categories = ["science", "development-tools"]

[features]
cuda = ["maidenx_internal/cuda"]

[dependencies]
maidenx_internal = { path = "crates/maindex_internal", version = "0.1.0-dev" }
